name: data-pipeline-workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  job1_data_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Start message
        run: echo "Starting data pipeline"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline
        run: python data_pipeline.py

      - name: Check for changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "update data hyperparameters"
          git push

      - name: Debug
        run: |
          echo "Checking contents of the directory"
          ls -R data

      - name: Save generated plot
        uses: actions/upload-artifact@v4
        with:
          name: generated-plot
          path: data/plots/training_plots.png

      - name: Save model as h5 file
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: data/model/cnn_cifar10.h5

      - name: Save confusion matrix as png
        uses: actions/upload-artifact@v4
        with:
          name: confusion-matrix
          path: data/plots/confusion_matrix.png

      - name: Save model summary as txt
        uses: actions/upload-artifact@v4
        with:
          name: model-summary
          path: data/model_summary.txt

  job2_ModelSumasTXT:
    needs: job1_data_pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Download model summary
        uses: actions/download-artifact@v4
        with:
          name: model-summary
          path: data

      - name: Verify model summary exists
        run: |
          if [ ! -f "./data/model_summary.txt" ]; then
            echo "Error: model summary does not exist."
            exit 1
          fi

      - name: Display model summary
        run: cat ./data/model_summary.txt

  job3_sending_report:
    needs: job1_data_pipeline
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: confusion-matrix
          path: data/plots

      - name: Download model summary
        uses: actions/download-artifact@v4
        with:
          name: model-summary
          path: data

      - name: Verify artifacts exist
        run: |
          if [ ! -f "./data/plots/confusion_matrix.png" ]; then
            echo "Error: confusion matrix does not exist."
            exit 1
          fi
          if [ ! -f "./data/model_summary.txt" ]; then
            echo "Error: model summary does not exist."
            exit 1
          fi

      - name: Send report with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '# Report' > report.md
          echo '## Confusion Matrix' >> report.md
          echo '![](./data/plots/confusion_matrix.png "Confusion Matrix")' >> report.md
          echo '## Model Summary' >> report.md
          echo '```' >> report.md
          cat ./data/model_summary.txt >> report.md
          echo '```' >> report.md
          cml comment create report.md
